# Generated by Django 5.0.6 on 2024-06-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking_operations', '0001_initial'),
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_deposit', to='user_account.account'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_withdrawal', to='user_account.account'),
        ),
    ]
