# Generated by Django 5.0.6 on 2024-06-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0003_alter_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
